# Q1. Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:
- Addition of 2 in all the element
- Multiply 3 with all the elements
- Divide every element by 2

In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
type(arr)
print('The array after addition of 2 in all the elements is:',arr+2)
print('The array after mutiplication of 3 in all the elements is:',arr*3)
print('The array after dividing every element by 2 is:',arr/2)

[1 2 3 4 5]
The array after addition of 2 in all the elements is: [3 4 5 6 7]
The array after mutiplication of 3 in all the elements is: [ 3  6  9 12 15]
The array after dividing every element by 2 is: [0.5 1.  1.5 2.  2.5]


# Q2. Questions on Basic NumPy Array:
- Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
- Find the most frequent value and their indice(s) in the following arrays:
    - x = np.array([1,2,3,4,5,1,2,1,1,1])
    - y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [4]:
arr=np.array([1,2,3,6,4,5])
print('The reversed array is:',arr[::-1])

def most_freq(arr):
    values,index,count=np.unique(arr,return_index=True,return_counts=True)
    ind=np.where(count==np.max(count))
    return values[ind],count[ind]   
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])
print(f'Most frequent element in {x} is: {most_freq(x)[0]} and its frequency is: {most_freq(x)[1]}')
print(f'Most frequent element in {y} is: {most_freq(y)[0]} and its frequency is: {most_freq(y)[1]}')

The reversed array is: [5 4 6 3 2 1]
Most frequent element in [1 2 3 4 5 1 2 1 1 1] is: [1] and its frequency is: [5]
Most frequent element in [1 1 1 2 3 4 2 4 3 3] is: [1 3] and its frequency is: [3 3]


# Q3. For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access elements using row and column indices as follows:
- Access 1st row, 2nd column
- Access 3rd row, 1st column

In [6]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print('First row and second column is:'arr[0,1])
print(arr[2,0])

20
70


## Q4. Write program to create an 1-D NumPy array named <<'Your' Name>> with evenly spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array. Find the transpose of this array using reshape() attribute. Can we do the same with T attribute?

In [8]:
Rhumeet=np.array(np.linspace(10,100,25))
print('Dimension of array is:',Rhumeet.ndim)
print('Shape of array is:',Rhumeet.shape)
print('Total elements in array is:',Rhumeet.size)
print('Data type of element of array is:',Rhumeet.dtype)
print('Total bytes consumed by array is:',Rhumeet.itemsize*Rhumeet.size)
print('Transpose of array is:',Rhumeet.reshape(Rhumeet.size,1))
print('Transpose of array is:',Rhumeet.T)

Dimension of array is: 1
Shape of array is: (25,)
Total elements in array is: 25
Data type of element of array is: float64
Total bytes consumed by array is: 200
Transpose of array is: [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose of array is: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


## Q5. Create a 2-D Array of three rows and four columns, named ucs420_<'your_name'>> with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements. Reshape the array to four rows and three columns and name it as reshaped_ ucs420_<'your_name'>>. Resize the array to two rows and three columns and name it as resized_ ucs420_<'your_name'>>.

In [10]:
ucs420_Rhumeet=np.array([10,20,30,40,50,60,70,80,90,15,20,35])
ucs420_Rhumeet=ucs420_Rhumeet.reshape(3,4)
print(ucs420_Rhumeet)
print(f'Mean of all elements = {np.mean(ucs420_Rhumeet)}')
print(f'Median of all elements = {np.median(ucs420_Rhumeet)}')
print(f'Max of all elements = {np.max(ucs420_Rhumeet)}')
print(f'Min of all elements = {np.min(ucs420_Rhumeet)}')
print(f'Unique elements = {np.unique(ucs420_Rhumeet)}')

reshaped_ucs420_Rhumeet=ucs420_Rhumeet.reshape(4,3)
print(reshaped_ucs420_Rhumeet)
resized_ucs420_Rhumeet=np.resize(reshaped_ucs420_Rhumeet,(2,3))
resized_ucs420_Rhumeet

[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean of all elements = 43.333333333333336
Median of all elements = 37.5
Max of all elements = 90
Min of all elements = 10
Unique elements = [10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


array([[10, 20, 30],
       [40, 50, 60]])